# Generated by Django 3.0.7 on 2020-07-03 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etapa3', '0002_auto_20200703_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'managed': False},
        ),
    ]
